"""init

Revision ID: 1011b757d078
Revises: 
Create Date: 2021-03-22 06:28:46.620697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1011b757d078'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tg_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tg_id', sa.Integer(), nullable=True),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('chat_id', sa.Integer(), nullable=True),
    sa.Column('start_timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tg_user_chat_id'), 'tg_user', ['chat_id'], unique=False)
    op.create_index(op.f('ix_tg_user_start_timestamp'), 'tg_user', ['start_timestamp'], unique=False)
    op.create_index(op.f('ix_tg_user_tg_id'), 'tg_user', ['tg_id'], unique=True)
    op.create_table('emmet_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tgUser_tg_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=32), nullable=True),
    sa.Column('template', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['tgUser_tg_id'], ['tg_user.tg_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emmet_templates_title'), 'emmet_templates', ['title'], unique=False)
    op.create_table('tg_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tgUser_tg_id', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tgUser_tg_id'], ['tg_user.tg_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tg_sessions_start_time'), 'tg_sessions', ['start_time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tg_sessions_start_time'), table_name='tg_sessions')
    op.drop_table('tg_sessions')
    op.drop_index(op.f('ix_emmet_templates_title'), table_name='emmet_templates')
    op.drop_table('emmet_templates')
    op.drop_index(op.f('ix_tg_user_tg_id'), table_name='tg_user')
    op.drop_index(op.f('ix_tg_user_start_timestamp'), table_name='tg_user')
    op.drop_index(op.f('ix_tg_user_chat_id'), table_name='tg_user')
    op.drop_table('tg_user')
    # ### end Alembic commands ###
